// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20190611110931_postsAndCommentsSoftDelete")]
    partial class postsAndCommentsSoftDelete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 9,
                            Body = "Libero provident ut unde occaecati qui vel.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(4559),
                            IsDeleted = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(5131)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 5,
                            Body = "Voluptatum ab quo.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6133),
                            IsDeleted = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6148)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 5,
                            Body = "Facere odio provident nobis ducimus saepe quod doloribus.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6292),
                            IsDeleted = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6305)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 12,
                            Body = "Nemo sapiente quia.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6408),
                            IsDeleted = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6421)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 16,
                            Body = "Voluptas reiciendis doloribus ea optio ducimus perferendis asperiores est.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6536),
                            IsDeleted = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6543)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Body = "Magnam cupiditate dolorum magnam nihil voluptate expedita exercitationem.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6702),
                            IsDeleted = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6709)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 8,
                            Body = "Autem ex enim placeat fugit quasi odio accusantium ut.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6799),
                            IsDeleted = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6806)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            Body = "Ut reiciendis nemo.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6873),
                            IsDeleted = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6879)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            Body = "Eligendi tempore quia quam ut maiores dolore.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6958),
                            IsDeleted = false,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(6965)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            Body = "Assumenda rerum vel possimus et.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7038),
                            IsDeleted = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7046)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 20,
                            Body = "Eum cumque ut.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7111),
                            IsDeleted = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7118)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 15,
                            Body = "Dolor minima sapiente ducimus eum enim in aliquid.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7219),
                            IsDeleted = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7226)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 11,
                            Body = "Odio id quis aut quia.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7303),
                            IsDeleted = false,
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7311)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 12,
                            Body = "Sit quaerat expedita.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7374),
                            IsDeleted = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7381)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 17,
                            Body = "Aperiam dolor ullam tempore quis dolorum.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7454),
                            IsDeleted = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7462)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 19,
                            Body = "Quidem et accusantium quibusdam doloremque repellendus.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7542),
                            IsDeleted = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7549)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 18,
                            Body = "Eaque ducimus numquam animi.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7617),
                            IsDeleted = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7624)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 4,
                            Body = "Adipisci velit et.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7691),
                            IsDeleted = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7698)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 11,
                            Body = "Est molestiae doloremque ut.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7783),
                            IsDeleted = false,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7790)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 15,
                            Body = "Vel sequi sed aut quia minus earum ullam.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7874),
                            IsDeleted = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 937, DateTimeKind.Local).AddTicks(7881)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 20,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(2840),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(3300),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 17,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(3937),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(3949),
                            UserId = 6
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(3991),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(3999),
                            UserId = 19
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 17,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4034),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4040),
                            UserId = 10
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 19,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4075),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4081),
                            UserId = 6
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 20,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4116),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4122),
                            UserId = 16
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4156),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4162),
                            UserId = 12
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 9,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4196),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4202),
                            UserId = 5
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4237),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4243),
                            UserId = 10
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 15,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4275),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4281),
                            UserId = 12
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4314),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4320),
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 15,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4473),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4481),
                            UserId = 4
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 11,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4521),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4527),
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 17,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4561),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4567),
                            UserId = 15
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 13,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4601),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4607),
                            UserId = 12
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 9,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4640),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4646),
                            UserId = 10
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4680),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4686),
                            UserId = 5
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4718),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4724),
                            UserId = 10
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4758),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4764),
                            UserId = 20
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 17,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4797),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 953, DateTimeKind.Local).AddTicks(4803),
                            UserId = 21
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("URL");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(1462),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/andysolomon/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(8141)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9105),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/krystalfister/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9118)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9158),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jonsgotwood/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9165)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9287),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jefffis/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9294)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9330),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/karlkanall/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9336)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9368),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/rawdiggie/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9374)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9406),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/constantx/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9412)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9443),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/dmitriychuta/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9449)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9479),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/cboller1/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9485)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9514),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/felipeapiress/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9520)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9549),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/badlittleduck/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9555)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9586),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/kinday/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9592)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9620),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/mattlat/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9626)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9655),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/balintorosz/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9661)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9690),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/wintopia/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9696)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9727),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/dshster/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9733)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9763),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/silv3rgvn/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9768)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9798),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/meelford/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9804)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9834),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/dgclegg/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9840)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9869),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/randomlies/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 733, DateTimeKind.Local).AddTicks(9875)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(4958),
                            URL = "https://picsum.photos/640/480/?image=24",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5427)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5597),
                            URL = "https://picsum.photos/640/480/?image=434",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5609)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5645),
                            URL = "https://picsum.photos/640/480/?image=484",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5652)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5682),
                            URL = "https://picsum.photos/640/480/?image=532",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5688)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5773),
                            URL = "https://picsum.photos/640/480/?image=355",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5779)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5810),
                            URL = "https://picsum.photos/640/480/?image=213",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5816)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5845),
                            URL = "https://picsum.photos/640/480/?image=445",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5851)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5879),
                            URL = "https://picsum.photos/640/480/?image=832",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5885)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5913),
                            URL = "https://picsum.photos/640/480/?image=788",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5919)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5946),
                            URL = "https://picsum.photos/640/480/?image=777",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5952)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5979),
                            URL = "https://picsum.photos/640/480/?image=401",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(5985)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6012),
                            URL = "https://picsum.photos/640/480/?image=622",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6017)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6044),
                            URL = "https://picsum.photos/640/480/?image=552",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6050)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6077),
                            URL = "https://picsum.photos/640/480/?image=71",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6083)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6112),
                            URL = "https://picsum.photos/640/480/?image=1077",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6117)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6145),
                            URL = "https://picsum.photos/640/480/?image=248",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6151)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6259),
                            URL = "https://picsum.photos/640/480/?image=8",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6265)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6298),
                            URL = "https://picsum.photos/640/480/?image=846",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6304)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6332),
                            URL = "https://picsum.photos/640/480/?image=92",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6337)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6366),
                            URL = "https://picsum.photos/640/480/?image=95",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 739, DateTimeKind.Local).AddTicks(6371)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("PreviewId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 11,
                            Body = @"Explicabo ducimus odio hic voluptas asperiores.
Id est quas nihil neque quia.
Quo ipsam est tempore ullam voluptatibus.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(3492),
                            IsDeleted = false,
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(3972)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 8,
                            Body = "quis",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(5098),
                            IsDeleted = false,
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(5114)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 4,
                            Body = "Voluptatem voluptas natus et. Impedit modi voluptatem illum animi qui delectus deserunt voluptates. Tempore voluptate facere magnam. Consequatur repudiandae magnam voluptatem ea est id.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(7686),
                            IsDeleted = false,
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(7701)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Body = "Dolor dolores officia quia. Molestias nemo soluta corrupti illo temporibus architecto nulla perferendis. Qui sed et tempore. Id expedita et odit beatae ullam dolore.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(7966),
                            IsDeleted = false,
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(7973)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Body = "aut",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(8038),
                            IsDeleted = false,
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(8044)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            Body = "Aspernatur voluptatem a consequatur eveniet dignissimos similique magni possimus.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(9669),
                            IsDeleted = false,
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(9681)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 11,
                            Body = "Voluptate sit vitae sed adipisci officiis.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(9789),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(9796)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 12,
                            Body = "deleniti",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(9849),
                            IsDeleted = false,
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(9855)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 21,
                            Body = "In totam earum.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(9926),
                            IsDeleted = false,
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 929, DateTimeKind.Local).AddTicks(9933)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 18,
                            Body = @"Voluptatem neque consequatur omnis.
Aperiam non tempore voluptatibus.
Debitis vero consequatur dicta earum in possimus et omnis ut.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(157),
                            IsDeleted = false,
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(164)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 12,
                            Body = "Ex asperiores nam vel veniam modi rerum neque. Possimus et est quam quo. Asperiores reprehenderit et sed nobis ea minima.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(330),
                            IsDeleted = false,
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(337)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 9,
                            Body = "Quo possimus a.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(453),
                            IsDeleted = false,
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(461)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 15,
                            Body = "Eos aut ipsa eos vero optio cum.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(549),
                            IsDeleted = false,
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(556)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 11,
                            Body = @"Pariatur suscipit non.
Ad facilis laboriosam expedita iste.
Architecto et eos ducimus.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(686),
                            IsDeleted = false,
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(692)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 7,
                            Body = "sed",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(743),
                            IsDeleted = false,
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(749)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 11,
                            Body = @"Et praesentium magni provident et.
Eligendi impedit quod neque et sint placeat.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(919),
                            IsDeleted = false,
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(926)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 15,
                            Body = @"Est consequatur et.
Ut quisquam velit et dolorem eos quos quis.
Voluptate est inventore fuga vel ratione fugit sed magni eos.
Sit laboriosam rerum recusandae qui voluptas est.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(1126),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(1132)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 8,
                            Body = "ut",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(1259),
                            IsDeleted = false,
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(1266)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 3,
                            Body = "et",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(1318),
                            IsDeleted = false,
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(1324)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 15,
                            Body = "Fugiat eius quis neque explicabo.",
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(1400),
                            IsDeleted = false,
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 930, DateTimeKind.Local).AddTicks(1407)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(2457),
                            IsLike = true,
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(2937),
                            UserId = 7
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3673),
                            IsLike = true,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3688),
                            UserId = 11
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3731),
                            IsLike = true,
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3738),
                            UserId = 10
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3829),
                            IsLike = true,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3836),
                            UserId = 13
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3875),
                            IsLike = true,
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3882),
                            UserId = 19
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3917),
                            IsLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3923),
                            UserId = 11
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3957),
                            IsLike = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3963),
                            UserId = 17
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(3996),
                            IsLike = true,
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4002),
                            UserId = 16
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4036),
                            IsLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4042),
                            UserId = 19
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4074),
                            IsLike = true,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4079),
                            UserId = 11
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4114),
                            IsLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4119),
                            UserId = 17
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4152),
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4158),
                            UserId = 15
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4191),
                            IsLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4197),
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4230),
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4236),
                            UserId = 18
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4268),
                            IsLike = false,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4273),
                            UserId = 17
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4308),
                            IsLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4314),
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4348),
                            IsLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4353),
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4388),
                            IsLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4394),
                            UserId = 15
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4427),
                            IsLike = false,
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4433),
                            UserId = 20
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4465),
                            IsLike = true,
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 946, DateTimeKind.Local).AddTicks(4471),
                            UserId = 13
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Expires");

                    b.Property<string>("Token");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 769, DateTimeKind.Local).AddTicks(3207),
                            Email = "Reba.Runte26@yahoo.com",
                            Password = "MJ0bIDYeDKw9Au4snP/C+xeEEKWgcLcL5K6b5DERsa4=",
                            Salt = "PXEQ14cme93rM3KPu2n78wa21EP1pvTMeYuxWQFvYjw=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 769, DateTimeKind.Local).AddTicks(3762),
                            UserName = "Gillian.Gaylord67"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 776, DateTimeKind.Local).AddTicks(9915),
                            Email = "Ryan_Hoeger@hotmail.com",
                            Password = "9y4bIY5GTLJArHV0nOioKbwWPXqkwl5nQjJEIhqFYJM=",
                            Salt = "bxzauW6OW6VK7VVsxYCu9uFRpLu5IH8lQUsaH5Mb3XE=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 776, DateTimeKind.Local).AddTicks(9931),
                            UserName = "Reese.Schumm15"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 784, DateTimeKind.Local).AddTicks(3819),
                            Email = "Eryn54@yahoo.com",
                            Password = "Zd8ooghyNe/GBDKKi5LwIqKUsP3ggNaqBdIqCbgXgwQ=",
                            Salt = "fL+lx93j25gpOigYyUoJMUIu0Lu3CnxiV2BP8yLBpoA=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 784, DateTimeKind.Local).AddTicks(3828),
                            UserName = "Finn.Rosenbaum55"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 792, DateTimeKind.Local).AddTicks(341),
                            Email = "Alexander_Ebert@hotmail.com",
                            Password = "RJoncAnsiTXO1aSivQln/9zvUKrsk3An879R5F1Qg54=",
                            Salt = "Q5j4u/95j1XPmk1IdeG4GhrdvK8JjIJNLC7dUWShKQQ=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 792, DateTimeKind.Local).AddTicks(352),
                            UserName = "Dale58"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 799, DateTimeKind.Local).AddTicks(4209),
                            Email = "Andreanne.Beer@hotmail.com",
                            Password = "3tw2/vGThYJX9tgCpEydqD7SwyyoDXv4RUjEBQ9wgBw=",
                            Salt = "61jgkyaovyCRThyVbA0maM6UR0Y7+apjDaTQfgD6A8I=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 799, DateTimeKind.Local).AddTicks(4223),
                            UserName = "Timmy56"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 806, DateTimeKind.Local).AddTicks(8096),
                            Email = "Steve12@hotmail.com",
                            Password = "Yc0GvXblybGcr8YwiJRyovHzIAJ+IaDJ80sZDctmk+Q=",
                            Salt = "kHwHu6fXPzeexOs1g3+Oj+QR63Pr3vfeQWwsZbztMZo=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 806, DateTimeKind.Local).AddTicks(8104),
                            UserName = "Helena.Schneider68"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 814, DateTimeKind.Local).AddTicks(4785),
                            Email = "King_Pfeffer@hotmail.com",
                            Password = "GmkReezYUQ9KjJ+rtdXap9BfqFxrmDnWDylhk9o6rW4=",
                            Salt = "KKQJN9A4ZjhOi1p8tgFrHMacdXAMvnQBHbT0cJplpSM=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 814, DateTimeKind.Local).AddTicks(4797),
                            UserName = "Kris.Sporer"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 821, DateTimeKind.Local).AddTicks(8779),
                            Email = "Sandra.Schumm53@yahoo.com",
                            Password = "lTItV6HkO3LRxkBzuASiMCwEGJBotVAx2mnQKH7GHc8=",
                            Salt = "e9kpZkXixfbciwW1+ocwHyuw9fCfKiYpKZ+6mqYhTyg=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 821, DateTimeKind.Local).AddTicks(8793),
                            UserName = "Dianna_Cummerata81"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 829, DateTimeKind.Local).AddTicks(2919),
                            Email = "Albina_Schamberger21@hotmail.com",
                            Password = "IS+Pb1SngyhRO93aUeFqGZW/NgDKbnY7bcLHD/6+Og4=",
                            Salt = "4OVN9g7/AH3bsvAZ6bshQSh9EKXJeNqXiIlsBCSHdXQ=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 829, DateTimeKind.Local).AddTicks(2928),
                            UserName = "Korey.Feeney"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 836, DateTimeKind.Local).AddTicks(6640),
                            Email = "Berniece37@yahoo.com",
                            Password = "4NUenjI6t/ro3e35S4ooFJ2rgswYofu/ffT00ncQRns=",
                            Salt = "ahhCW0ahV63wDB4amuY8IktHcFUpRwdEFxCbzWzdKo8=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 836, DateTimeKind.Local).AddTicks(6647),
                            UserName = "Elias.Erdman"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 844, DateTimeKind.Local).AddTicks(1217),
                            Email = "Alphonso.Shields4@hotmail.com",
                            Password = "7KuiIW/g9mLfLi6GAhjttqwi/vFW4HZ98wiMWoZo4r0=",
                            Salt = "V/bzW1uSbPm//veM0DP51yxXuELc2hNJJ8JEhiedT0s=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 844, DateTimeKind.Local).AddTicks(1230),
                            UserName = "Fannie.Lindgren86"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 851, DateTimeKind.Local).AddTicks(8471),
                            Email = "Karl_Veum@gmail.com",
                            Password = "uCJQggUVsM5WmER0ah8zsP4uSt+u8VVwEHdjlGj5yrw=",
                            Salt = "i0tcHFMBGDIUcC4srG+1yzLZkN59gISEXbQB80g/xc0=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 851, DateTimeKind.Local).AddTicks(8487),
                            UserName = "Kavon2"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 859, DateTimeKind.Local).AddTicks(2739),
                            Email = "Keara29@gmail.com",
                            Password = "7t/VU9F9W2cIoGXqzOYo9EaNz8/npCfVk9akAMwP6/Q=",
                            Salt = "s3CCUU1AVkhTrj86a0+2/s0Zey8WaBna/vysDrEN2as=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 859, DateTimeKind.Local).AddTicks(2754),
                            UserName = "Haylie.Kohler"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 866, DateTimeKind.Local).AddTicks(6616),
                            Email = "Jerod63@yahoo.com",
                            Password = "of2z8DrHeqS81tDcATvUvky5+FlzOXF1cpQGyIS1JE4=",
                            Salt = "A3hsWgkiC+eoJ4Ss7Man8j5jXLtIPt5ezdKzZznfbJo=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 866, DateTimeKind.Local).AddTicks(6626),
                            UserName = "Will.Reilly25"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 874, DateTimeKind.Local).AddTicks(3292),
                            Email = "Nolan.Smitham@yahoo.com",
                            Password = "baLOJ20WpAJxsNFsp2EyaqSPuy9Kh2kGbkL8xCwX1yw=",
                            Salt = "a2EMp1mOIW05FHff0FInB42FifMw+tnuKn1BoKjGqJA=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 874, DateTimeKind.Local).AddTicks(3306),
                            UserName = "Abigail_Hyatt10"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 881, DateTimeKind.Local).AddTicks(7430),
                            Email = "Luigi_Wiegand23@hotmail.com",
                            Password = "4xvWI60nTeNYZAjND2Y1gX51lymU+RP+FLrWNdEaRLw=",
                            Salt = "NF9tj4bDKCgDrYgxrseO3IuuvtkAoJhx9DrEpOomL7s=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 881, DateTimeKind.Local).AddTicks(7440),
                            UserName = "Solon43"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 889, DateTimeKind.Local).AddTicks(1388),
                            Email = "Veronica67@hotmail.com",
                            Password = "NLy+Wj/IUAgV0gw2wbYP5rNmzG2JwG8HNvyqY0LMQKM=",
                            Salt = "EJvj7ouu/UxqkckJYUyPDOGPuJNj9v3lGSbm3vGt4KE=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 889, DateTimeKind.Local).AddTicks(1396),
                            UserName = "Alyson_Gleichner"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 896, DateTimeKind.Local).AddTicks(5157),
                            Email = "Laury1@hotmail.com",
                            Password = "mq8vefbIVP6a80sMKenXLsjOI3d0YSzcod0HcDFfrDI=",
                            Salt = "CzEqL+BFo9VEaQkwVq2RfhLN2VlinalvZ7NCHLpTBdM=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 896, DateTimeKind.Local).AddTicks(5165),
                            UserName = "Gerhard_Leuschke68"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 903, DateTimeKind.Local).AddTicks(8865),
                            Email = "Rick89@yahoo.com",
                            Password = "u/icI/cnSkMtsVkgNQ6uM/yNgYwdR+W1AJgwLWfQcDo=",
                            Salt = "NYd/Co0qVapwwqRuRTQjS7vdLbB1diYaXp+KebgJGIo=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 903, DateTimeKind.Local).AddTicks(8873),
                            UserName = "Marcus_Hyatt"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 911, DateTimeKind.Local).AddTicks(5742),
                            Email = "Jeremie_Moore@gmail.com",
                            Password = "CPIO7mLIg1mWaMGfCCtzlOod1qcR9OhAOb8MY2hhsZI=",
                            Salt = "Nek+GfUohVEH20iYDcF1hEB4n8wTz+DnG2TyB4r66BI=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 911, DateTimeKind.Local).AddTicks(5757),
                            UserName = "Carson.Anderson64"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 919, DateTimeKind.Local).AddTicks(343),
                            Email = "test@gmail.com",
                            Password = "lN9L/KtmGjvgftDrvscxHcksq0o2965CZ7B0CCt4yFQ=",
                            Salt = "spq8zvBc9E3RdPuPPfCFphen1Fx0+1X1PiAMUX7AuKk=",
                            UpdatedAt = new DateTime(2019, 6, 11, 14, 9, 30, 919, DateTimeKind.Local).AddTicks(343),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");
                });
#pragma warning restore 612, 618
        }
    }
}
